name: Sync webhook

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [main]
    paths: [.github/workflows/sync-webhook.yml]
  workflow_dispatch:

jobs:
  run:
    uses: Friedinger/configs/.github/workflows/action-sync-webhook.yml@ecb0f494bef8837f3ffc5ac40354edb9c6ad20ab # v1.1.0
    secrets:
      WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
