name: Sync labels

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [main]
    paths: [.github/workflows/sync-labels.yml]
  workflow_dispatch:

jobs:
  run:
    uses: Friedinger/configs/.github/workflows/action-sync-labels.yml@e3ea032b22e069bb5c6ca61a43843503bc092aff # v1.0.0
    permissions:
      issues: write
