name: Sync labels

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [main]
    paths: [.github/workflows/sync-labels.yml]
  workflow_dispatch:

jobs:
  run:
    uses: Friedinger/Configs/.github/workflows/action-sync-labels.yml@1010d86e59d6446d2726d14d82662a6d8b5ef490 # main
    permissions:
      issues: write
