name: Sync labels

on:
  schedule:
    - cron: "0 3 * * 0"
  push:
    branches: [main]
    paths: [.github/workflows/sync-labels.yml]
  workflow_dispatch:

jobs:
  run:
    uses: Friedinger/configs/.github/workflows/action-sync-labels.yml@6bf9f3725ccc8b59f39c62672cfd7b626ebba33c # v1.2.2
    permissions:
      issues: write
